# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.10"

gem "colorize", "~> 0.8.1"

gem "artii", "~> 2.1"

gem "tty-progressbar", "~> 0.18.2"

gem "tty-link", "~> 0.1.1"
